<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>CoreECS</PackageId>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>CoreECS</RootNamespace>
        <LangVersion>9</LangVersion>
        <AssemblyName>CoreECS</AssemblyName>
        <PackageId>CoreECS</PackageId>
        <Title>CoreECS</Title>
        <Authors>Cardidi</Authors>
        <Description>A lightweight, easy-to-use Entity-Component-System (ECS) implementation designed for C#-based game applications.</Description>
        <Copyright>©Cardidi 2026</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/Cardidi/CoreECS</RepositoryUrl>
        <PackageTags>ECS;Entity Component System;Game;Game Development;C#;Unity;Toolkit</PackageTags>
        <RepositoryType>git</RepositoryType>
        <Company>Cardidi</Company>
        <Product>CoreECS</Product>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    </ItemGroup>
</Project>